build:
	g++ -Wno-deprecated classCarrito.cpp classCarrito.h classUsuario.cpp classUsuario.h classInventario.cpp classInventario.h classProducto.h classProducto.cpp main.cpp
	rm classCarrito.h.gch classUsuario.h.gch classInventario.h.gch classProducto.h.gch
	./a.out

	


